#%%
import sqlite3

conn = sqlite3.connect("../data/recommend.db")

c = conn.cursor()

c.execute(
    "CREATE TABLE QUERY (KEYWORD CHAR(20) PRIMARY KEY, PARAMS CHAR(200), ENCSECKEY CHAR(200), JSON_PATH CHAR(40));"
)
c.execute(
    "CREATE TABLE REQUEST (KEYWORD CHAR(20), TIME CHAR(20), USER_MAC CHAR(200), CHOICE INT, FOREIGN KEY (KEYWORD) REFERENCES QUERY(KEYWORD));"
)
c.execute(
    "CREATE TABLE PLAYLIST (PLAYLIST_ID CHAR(30) PRIMARY KEY, PLAYLIST_NAME CHAR(30), KEYWORD CHAR(20), FOREIGN KEY (KEYWORD) REFERENCES QUERY(KEYWORD));"
)
c.execute("CREATE TABLE MUSIC (MUSIC_ID CHAR(30), MUSIC_NAME CHAR(30));")
c.execute(
    "CREATE TABLE PLAYLIST_MUSIC (PLAYLIST_ID CHAR(30), MUSIC_ID CHAR(30), FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(PLAYLIST_ID), FOREIGN KEY (MUSIC_ID) REFERENCES MUSIC(MUSIC_ID));"
)
# SUPPORT DAILY UPDATE THE HOT MUSIC PLAYLIST

conn.commit()
#%%
conn.close()

# %%
